export const SELECT_TOOL_MSG = 'SELECT_TOOL'
export const SET_TOOL_FEATURE_VALUE_MSG = 'SET_TOOL_FEATURE_VALUE'

export const SET_SETTINGS_VALUE_MSG = 'SET_SETTINGS_VALUE'

export const TOOL_CURSOR_MOVE_MSG = 'TOOL_CURSOR_MOVE'
export const TOOL_CURSOR_LEAVE_MSG = 'TOOL_CURSOR_LEAVE'

export const CAMERA_ZOOM_MSG = 'CAMERA_ZOOM'
export const CAMERA_MOVE_START_MSG = 'CAMERA_MOVE_START'
export const CAMERA_MOVE_END_MSG = 'CAMERA_MOVE_END'
export const CAMERA_MOVE_MSG = 'CAMERA_MOVE'

export const SELECTION_MOVE_START_MSG = 'SELECTION_MOVE_START'
export const SELECTION_MOVE_END_MSG = 'SELECTION_MOVE_END'
export const SELECTION_MOVE_MSG = 'SELECTION_MOVE'

export const ADD_FROM_TEMPLATE_MSG = 'ADD_FROM_TEMPLATE'

export const SELECT_LEVEL_MSG = 'SELECT_LEVEL'

export const INSPECT_ENTITY_MSG = 'INSPECT_ENTITY'
export const INSPECTED_ENTITY_CHANGE_MSG = 'INSPECTED_ENTITY_CHANGE'

export const COMMAND_MSG = 'COMMAND'
export const COMMAND_UNDO_MSG = 'COMMAND_UNDO'
export const COMMAND_REDO_MSG = 'COMMAND_REDO'
export const COMMAND_CLEAN_MSG = 'COMMAND_CLEAN'
