export const SELECT_TOOL_MSG = 'SELECT_TOOL'
export const SET_TOOL_FEATURE_VALUE_MSG = 'SET_TOOL_FEATURE_VALUE'

export const CAMERA_ZOOM_MSG = 'CAMERA_ZOOM'
export const CAMERA_MOVE_START_MSG = 'CAMERA_MOVE_START'
export const CAMERA_MOVE_END_MSG = 'CAMERA_MOVE_END'
export const CAMERA_MOVE_MSG = 'CAMERA_MOVE'
